In [111]:
## 1. Projeto Cartão de Crédito

In [112]:
# Import de bibliotecas e dados
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import sys
sys.path
sys.executable
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
# Load dataset
df = pd.read_csv('datasets/cc_approvals.data',header=None) 
df.head()

  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [113]:
#df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       690 non-null    object
 1   1       690 non-null    object
 2   2       690 non-null    float64
 3   3       690 non-null    object
 4   4       690 non-null    object
 5   5       690 non-null    object
 6   6       690 non-null    object
 7   7       690 non-null    float64
 8   8       690 non-null    object
 9   9       690 non-null    object
 10  10      690 non-null    int64
 11  11      690 non-null    object
 12  12      690 non-null    object
 13  13      690 non-null    object
 14  14      690 non-null    int64
 15  15      690 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB

In [114]:
df.tail(20)

    0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670  b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671  b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672  a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [115]:
df = df.replace('?',np.nan)

In [116]:
df.tail(20)

      0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670    b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671    b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672    a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  NaN  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674    a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675    a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676    a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677    b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678    a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679    a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680    b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681    b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682    b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683    b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684    b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685    b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686    a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687    a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688    b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689    b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [117]:
df.fillna(df.mean(), inplace=True)
df.isnull().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [118]:
for col in df.columns:
    # Checar se a coluna é do tipo object 
    if df[col].dtypes == 'object':
        # Imputar com os valores mais frequentes
        df = df.fillna(df[col].value_counts().index[0])
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [119]:
le = LabelEncoder()

In [120]:
for col in df.columns:
    # Compare se o the dtype é object
    if df[col].dtypes=='object':
    # Use LabelEncoder para fazer a transformação numérica
        df[col]=le.fit_transform(df[col])
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
count,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.00000,690.000000,690.000000,690.000000,690.000000,690.000000
mean,0.695652,150.528986,4.758725,2.215942,1.466667,6.607246,5.994203,2.223406,0.523188,0.427536,2.40000,0.457971,0.176812,59.392754,1017.385507,0.555072
std,0.460464,96.188946,4.978163,0.477087,0.860126,4.412110,2.594506,3.346513,0.499824,0.495080,4.86294,0.498592,0.557869,48.231670,5210.102598,0.497318
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,71.000000,1.000000,2.000000,1.000000,2.000000,4.000000,0.165000,0.000000,0.000000,0.00000,0.000000,0.000000,23.000000,0.000000,0.000000
50%,1.000000,133.500000,2.750000,2.000000,1.000000,6.000000,8.000000,1.000000,1.000000,0.000000,0.00000,0.000000,0.000000,52.000000,5.000000,1.000000
75%,1.000000,226.000000,7.207500,2.000000,1.000000,11.000000,8.000000,2.625000,1.000000,1.000000,3.00000,1.000000,0.000000,96.000000,395.500000,1.000000
max,1.000000,349.000000,28.000000,3.000000,3.000000,14.000000,9.000000,28.500000,1.000000,1.000000,67.00000,1.000000,2.000000,170.000000,100000.000000,1.000000

In [121]:
# Drop the features 11 and 13 and convert the DataFrame to a NumPy array
df = df.drop([df.columns[11], df.columns[13]], axis=1)
df = df.values
X = df[:,0:13] 
y = df[:,13]
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.33, random_state=42)
X_treino

array([[  0.  ,  87.  ,   2.5 , ...,   0.  ,   0.  , 456.  ],
       [  1.  , 182.  ,   2.75, ...,   6.  ,   0.  ,   0.  ],
       [  1.  , 170.  ,   1.5 , ...,   0.  ,   0.  , 122.  ],
       ...,
       [  1.  , 217.  ,   0.  , ...,   0.  ,   1.  ,   0.  ],
       [  1.  ,  33.  ,   0.  , ...,   4.  ,   0.  ,   1.  ],
       [  1.  ,  29.  ,   5.  , ...,   2.  ,   0.  ,  38.  ]])

In [122]:
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX_treino = scaler.fit_transform(X_treino)
rescaledX_teste = scaler.fit_transform(X_teste)

In [123]:
# Import LogisticRegression
# Instantiate a LogisticRegression classifier with default parameter values
logreg = LogisticRegression()
# Fit logreg to the train set
logreg.fit(rescaledX_treino,y_treino)

LogisticRegression()

In [124]:
#Matriz de Confusão

y_pred = logreg.predict(rescaledX_teste) # Use logreg to predict instances from the test set and store it
print(" Precisão do Classificador é: ", logreg.score(rescaledX_teste,y_teste))
print(confusion_matrix(y_teste,y_pred))  #  matriz de confusão do modelo logreg

 Precisão do Classificador é:  0.8377192982456141
[[92 11]
 [26 99]]

In [125]:
tol = [0.01,0.001,0.0001]
max_iter = [100,150,200]
param_grid = dict(tol=tol,max_iter=max_iter)
print(param_grid)

{'tol': [0.01, 0.001, 0.0001], 'max_iter': [100, 150, 200]}

In [126]:
grid_model = GridSearchCV(estimator=logreg, param_grid=param_grid, cv=5)
rescaledX = scaler.fit_transform(X)
grid_model_result = grid_model.fit(rescaledX, y)
best_score, best_params = grid_model_result.best_score_,grid_model_result.best_params_
print("Best: %f using %s" % (best_score, best_params))

Best: 0.850725 using {'max_iter': 100, 'tol': 0.01}